// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC65R0VDTduxmKlcJMp3obJ1AikmWqxsP0',
    appId: '1:536466204456:web:8cd370bc53d9abe240121d',
    messagingSenderId: '536466204456',
    projectId: 'calora-shurashipai',
    authDomain: 'calora-shurashipai.firebaseapp.com',
    storageBucket: 'calora-shurashipai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBrHfTxrkgaCFJwZezD7xjyEQM4u0IgyI',
    appId: '1:536466204456:android:14623da8ce38738e40121d',
    messagingSenderId: '536466204456',
    projectId: 'calora-shurashipai',
    storageBucket: 'calora-shurashipai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOfIrrTSG3LaMV_7jlJtShM9RTnNl45nY',
    appId: '1:536466204456:ios:bb849dd92a77b81a40121d',
    messagingSenderId: '536466204456',
    projectId: 'calora-shurashipai',
    storageBucket: 'calora-shurashipai.firebasestorage.app',
    iosBundleId: 'com.example.calora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOfIrrTSG3LaMV_7jlJtShM9RTnNl45nY',
    appId: '1:536466204456:ios:bb849dd92a77b81a40121d',
    messagingSenderId: '536466204456',
    projectId: 'calora-shurashipai',
    storageBucket: 'calora-shurashipai.firebasestorage.app',
    iosBundleId: 'com.example.calora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC65R0VDTduxmKlcJMp3obJ1AikmWqxsP0',
    appId: '1:536466204456:web:862bfafcb9c5668c40121d',
    messagingSenderId: '536466204456',
    projectId: 'calora-shurashipai',
    authDomain: 'calora-shurashipai.firebaseapp.com',
    storageBucket: 'calora-shurashipai.firebasestorage.app',
  );
}
